Added alternative way of using for omgservers-ctl

diff --git a/omgservers-sidecontainer/omgservers-ctl/src/main/docker/omgserversctl b/omgservers-sidecontainer/omgservers-ctl/src/main/docker/omgserversctl
--- a/omgservers-sidecontainer/omgservers-ctl/src/main/docker/omgserversctl
+++ b/omgservers-sidecontainer/omgservers-ctl/src/main/docker/omgserversctl
@@ -67,6 +67,18 @@ help() {
   if [ -z "$1" -o "$1" = "developer" -o "$1" = "developer createProject" ]; then
     echo " omgserversctl developer createProject"
   fi
+  if [ -z "$1" -o "$1" = "developer" -o "$1" = "developer useProject" ]; then
+    echo " omgserversctl developer useProject <project_id>"
+  fi
+  if [ -z "$1" -o "$1" = "developer" -o "$1" = "developer printProject" ]; then
+    echo " omgserversctl developer printProject"
+  fi
+  if [ -z "$1" -o "$1" = "developer" -o "$1" = "developer useStage" ]; then
+    echo " omgserversctl developer useStage <stage_id>"
+  fi
+  if [ -z "$1" -o "$1" = "developer" -o "$1" = "developer printStage" ]; then
+    echo " omgserversctl developer printStage"
+  fi
   if [ -z "$1" -o "$1" = "developer" -o "$1" = "developer getTenantDashboard" ]; then
     echo " omgserversctl developer getTenantDashboard"
   fi
@@ -107,6 +119,8 @@ environment_useEnvironment() {
 # ADMIN
 
 admin_useCredentials() {
+  internal_useEnvironment
+
   ADMIN_USER_ID=$1
   ADMIN_PASSWORD=$2
 
@@ -125,6 +139,8 @@ admin_useCredentials() {
 }
 
 admin_printCurrent() {
+  internal_useEnvironment
+
   ADMIN_USER_ID=${OMGSERVERSCTL_ADMIN_USER_ID}
   ADMIN_USER_PASSWORD=${OMGSERVERSCTL_ADMIN_PASSWORD}
   ADMIN_TOKEN=${OMGSERVERSCTL_ADMIN_TOKEN}
@@ -142,6 +158,8 @@ admin_printCurrent() {
 }
 
 admin_createToken() {
+  internal_useEnvironment
+
   ADMIN_USER_ID=${OMGSERVERSCTL_ADMIN_USER_ID}
   ADMIN_PASSWORD=${OMGSERVERSCTL_ADMIN_PASSWORD}
 
@@ -189,6 +207,8 @@ admin_createToken() {
 # SUPPORT
 
 support_useCredentials() {
+  internal_useEnvironment
+
   SUPPORT_USER_ID=$1
   SUPPORT_PASSWORD=$2
 
@@ -208,6 +228,8 @@ support_useCredentials() {
 }
 
 support_printCurrent() {
+  internal_useEnvironment
+
   SUPPORT_USER_ID=${OMGSERVERSCTL_SUPPORT_USER_ID}
   SUPPORT_USER_PASSWORD=${OMGSERVERSCTL_SUPPORT_USER_PASSWORD}
   SUPPORT_TOKEN=${OMGSERVERSCTL_SUPPORT_TOKEN}
@@ -225,6 +247,8 @@ support_printCurrent() {
 }
 
 support_createToken() {
+  internal_useEnvironment
+
   SUPPORT_USER_ID=$OMGSERVERSCTL_SUPPORT_USER_ID
   SUPPORT_PASSWORD=$OMGSERVERSCTL_SUPPORT_USER_PASSWORD
 
@@ -269,6 +293,8 @@ support_createToken() {
 }
 
 support_createTenant() {
+  internal_useEnvironment
+
   SUPPORT_TOKEN=$OMGSERVERSCTL_SUPPORT_TOKEN
 
   if [ -z "${SUPPORT_TOKEN}" ]; then
@@ -310,6 +336,8 @@ support_createTenant() {
 }
 
 support_deleteTenant() {
+  internal_useEnvironment
+
   SUPPORT_TOKEN=$OMGSERVERSCTL_SUPPORT_TOKEN
 
   if [ -z "${SUPPORT_TOKEN}" ]; then
@@ -361,6 +389,8 @@ support_deleteTenant() {
 }
 
 support_createDeveloper() {
+  internal_useEnvironment
+
   SUPPORT_TOKEN=$OMGSERVERSCTL_SUPPORT_TOKEN
 
   if [ -z "${SUPPORT_TOKEN}" ]; then
@@ -423,6 +453,8 @@ support_createDeveloper() {
 # DEVELOPER
 
 developer_printCurrent() {
+  internal_useEnvironment
+
   DEVELOPER_USER_ID=${OMGSERVERSCTL_DEVELOPER_USER_ID}
   DEVELOPER_PASSWORD=${OMGSERVERSCTL_DEVELOPER_USER_PASSWORD}
   DEVELOPER_TOKEN=${OMGSERVERSCTL_DEVELOPER_TOKEN}
@@ -440,6 +472,8 @@ developer_printCurrent() {
 }
 
 developer_createToken() {
+  internal_useEnvironment
+
   DEVELOPER_USER_ID=$OMGSERVERSCTL_DEVELOPER_USER_ID
   DEVELOPER_PASSWORD=$OMGSERVERSCTL_DEVELOPER_USER_PASSWORD
 
@@ -483,6 +517,8 @@ developer_createToken() {
 }
 
 developer_useCredentials() {
+  internal_useEnvironment
+
   DEVELOPER_USER_ID=$1
   DEVELOPER_PASSWORD=$2
 
@@ -501,6 +537,8 @@ developer_useCredentials() {
 }
 
 developer_useTenant() {
+  internal_useEnvironment
+
   TENANT_ID=$1
 
   if [ -z "${TENANT_ID}" ]; then
@@ -514,6 +552,8 @@ developer_useTenant() {
 }
 
 developer_printTenant() {
+  internal_useEnvironment
+
   TENANT_ID=$OMGSERVERSCTL_TENANT_ID
 
   if [ -z "${TENANT_ID}" ]; then
@@ -525,6 +565,8 @@ developer_printTenant() {
 }
 
 developer_createProject() {
+  internal_useEnvironment
+
   TENANT_ID=$OMGSERVERSCTL_TENANT_ID
 
   if [ -z "${TENANT_ID}" ]; then
@@ -589,6 +631,8 @@ developer_createProject() {
 }
 
 developer_getTenantDashboard() {
+  internal_useEnvironment
+
   TENANT_ID=$OMGSERVERSCTL_TENANT_ID
 
   if [ -z "${TENANT_ID}" ]; then
@@ -631,7 +675,65 @@ developer_getTenantDashboard() {
   open ~/.omgservers/temp/developer-get-tenant-dashboard_${TENANT_ID}.json
 }
 
+developer_useProject() {
+  internal_useEnvironment
+
+  PROJECT_ID=$1
+
+  if [ -z "${PROJECT_ID}" ]; then
+    help "developer useProject"
+    exit 1
+  fi
+
+  echo "export OMGSERVERSCTL_PROJECT_ID=${PROJECT_ID}" >> ~/.omgservers/environment
+
+  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Project was set, PROJECT_ID=$PROJECT_ID"
+}
+
+developer_printProject() {
+  internal_useEnvironment
+
+  PROJECT_ID=$OMGSERVERSCTL_PROJECT_ID
+
+  if [ -z "${PROJECT_ID}" ]; then
+    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current project was not found"
+    exit 1
+  fi
+
+  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Project was found, PROJECT_ID=${PROJECT_ID}"
+}
+
+developer_useStage() {
+  internal_useEnvironment
+
+  STAGE_ID=$1
+
+  if [ -z "${STAGE_ID}" ]; then
+    help "developer useStage"
+    exit 1
+  fi
+
+  echo "export OMGSERVERSCTL_STAGE_ID=${STAGE_ID}" >> ~/.omgservers/environment
+
+  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Stage was set, STAGE_ID=$STAGE_ID"
+}
+
+developer_printStage() {
+  internal_useEnvironment
+
+  STAGE_ID=$OMGSERVERSCTL_STAGE_ID
+
+  if [ -z "${STAGE_ID}" ]; then
+    echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) ERROR: Current stage was not found"
+    exit 1
+  fi
+
+  echo "$(date) $(echo $OMGSERVERSCTL_ENVIRONMENT_NAME) Stage was found, STAGE_ID=${STAGE_ID}"
+}
+
 developer_uploadVersion() {
+  internal_useEnvironment
+
   PROJECT_PATH=$1
 
   if [ -z "${PROJECT_PATH}" ]; then
@@ -713,26 +815,28 @@ developer_uploadVersion() {
 # INTERNAL
 
 internal_useEnvironment() {
-  if [ ! -d "~/.omgservers/temp" ]; then
-    mkdir -p ~/.omgservers/temp
-  fi
-  if [ ! -f "~/.omgservers/environment" ]; then
-    touch ~/.omgservers/environment
-  fi
-  if [ ! -f "~/.omgservers/logs" ]; then
-    touch ~/.omgservers/logs
-  fi
-
   source ~/.omgservers/environment
 
-  if [ -n "${OMGSERVERSCTL_ENVIRONMENT_NAME-}" ]; then
+  if [ -z "${OMGSERVERSCTL_ENVIRONMENT_NAME}" ]; then
+    echo "$(date) $(echo unknown) ERROR: Environment was not configured"
+    help "environment useEnvironment"
+    exit 1
+  else
     source ~/.omgservers/environment
   fi
 }
 
 # MAIN
 
-internal_useEnvironment
+if [ ! -d "~/.omgservers/temp" ]; then
+  mkdir -p ~/.omgservers/temp
+fi
+if [ ! -f "~/.omgservers/environment" ]; then
+  touch ~/.omgservers/environment
+fi
+if [ ! -f "~/.omgservers/logs" ]; then
+  touch ~/.omgservers/logs
+fi
 
 if [ -z "$1" -o "$1" = "help" ]; then
   help
@@ -756,15 +860,10 @@ if [ "$1" = "environment" ]; then
   exit 0
 fi
 
-if [ -z "${OMGSERVERSCTL_ENVIRONMENT_NAME}" ]; then
-  echo "$(date) $(echo unknown) ERROR: Environment was not selected"
-  exit 1
-fi
-
 # Admin
 if [ "$1" = "admin" ]; then
   if [ "$2" = "useCredentials" ]; then
-      admin_useCredentials $3 $4
+    admin_useCredentials $3 $4
   elif [ "$2" = "printCurrent" ]; then
     admin_printCurrent
   elif [ "$2" = "createToken" ]; then
@@ -803,6 +902,14 @@ elif [ "$1" = "developer" ]; then
       developer_printTenant
   elif [ "$2" = "createProject" ]; then
     developer_createProject
+  elif [ "$2" = "useProject" ]; then
+    developer_useProject $3
+  elif [ "$2" = "printProject" ]; then
+      developer_printProject
+  elif [ "$2" = "useStage" ]; then
+    developer_useStage $3
+  elif [ "$2" = "printStage" ]; then
+      developer_printStage
   elif [ "$2" = "getTenantDashboard" ]; then
     developer_getTenantDashboard
   elif [ "$2" = "uploadVersion" ]; then
